import type {
  VolunteerApplicant,
  GeoIncident,
  ActivityLogItem,
  HeroStatMetric,
} from './types';

export const ADMIN_HERO_STATS: HeroStatMetric[] = [
  {
    title: 'Volunteer Applications',
    value: '34',
    badge: '12 Urgent SOS',
    badgeType: 'error',
    subtitle: 'Pending direct nodal interview & clearance',
    footerText: 'Medical & SAR priority',
    actionText: 'Review All',
    icon: 'badge',
  },
  {
    title: 'Geo-Cam Citizen Triage',
    value: '8',
    badge: 'Anti-Prank ON',
    badgeType: 'neutral',
    subtitle: 'Hardware EXIF & CV validation required',
    footerText: 'Chamoli & Rudraprayag',
    actionText: 'Inspect EXIF',
    icon: 'camera_indoor',
  },
  {
    title: 'Transit Camps Occupancy',
    value: '87.4%',
    badge: 'Critical Saturation',
    badgeType: 'neutral',
    subtitle: 'Gauchar, Pipalkoti & Joshimath Hubs',
    footerText: 'Capacity Cap 1,200 cots',
    actionText: 'Manage Beds',
    icon: 'cottage',
  },
  {
    title: 'Active Gazette Directives',
    value: '3',
    badge: 'Sec 144 Enforced',
    badgeType: 'error',
    subtitle: 'Alaknanda Basin buffer zones active',
    footerText: 'Next review 18:00 IST',
    actionText: 'Issue Directive',
    icon: 'gavel',
  },
];

export const INITIAL_APPLICANTS: VolunteerApplicant[] = [
  {
    id: 'vol-1',
    name: 'Dr. Ananya Joshi',
    phone: '+91 98451 22891',
    govId: 'Aadhaar: •••• 8821',
    specialization: 'Paramedic / Trauma Specialist',
    specializationType: 'medical',
    sector: 'Joshimath Helipad Sector',
    availability: 'Immediate Dispatch Available',
    verificationBadge: 'DigiLocker Verified',
    status: 'pending',
  },
  {
    id: 'vol-2',
    name: 'Gurpreet S. Negi',
    phone: '+91 94120 77312',
    govId: 'Govt ID: DL-UK-2018',
    specialization: '4x4 Offroad Heavy Rescue',
    specializationType: 'vehicle',
    sector: 'Pipalkoti - Helang Corridor',
    availability: 'Equipped with winch & high clearance',
    verificationBadge: 'RTO Validated',
    status: 'pending',
  },
  {
    id: 'vol-3',
    name: 'Virendra Rawat (VU2ZUK)',
    phone: '+91 88710 44921',
    govId: 'WPC Lic: WPC-VU-91',
    specialization: 'Amateur Ham Radio Relayer',
    specializationType: 'radio',
    sector: 'Badrinath Pass Remote Node',
    availability: 'HF/VHF Portable Transceiver Rig',
    verificationBadge: 'DOT/WPC Cleared',
    status: 'pending',
  },
];

export const INITIAL_INCIDENTS: GeoIncident[] = [
  {
    id: 'inc-1',
    title: 'NH-7 Landslide Choke at Helang',
    severity: 'HIGH SEVERITY',
    locationText: 'Helang Bypass, KM Post 214',
    coordinates: '30.5512° N, 79.5638° E',
    timeAgo: '3 mins ago',
    photoUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAgDnkstDi-cUBXqn5yYQjBWHSeT0TfSnpr-TpXJIWWEy_AiTYw9SJ2D9yfDUjnFZpOtpPegN4fXJ6DghNITJvAzUQfX1GCMUWgNXSo6n75XQ53GE9vyC1qiYHXmanrIHdHjzqFM3xUBEB1XNAuRCp45mZjLCymjPXY86X7QxivN92X80y5HiNaBPYI3jM9oPItzdaAZ9p8hCNskKuDK0EbmkgdIZfc8vDnVcnHI-UMvvVw3mnYQ6o',
    gpsDelta: '1.4m (Hardware Match)',
    hardwareClockStatus: 'Synced (0.2s drift)',
    cvConfidence: 94.8,
    status: 'pending',
  },
  {
    id: 'inc-2',
    title: 'Pipalkoti Embankment Flash Rise',
    severity: 'MEDIUM RISK',
    locationText: 'Pipalkoti Ghat Embankment',
    coordinates: '30.4290° N, 79.3301° E',
    timeAgo: '11 mins ago',
    photoUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuApjHyvEyk8crF8jImgUr3jGs_cGD007FLqtvNUFk0uWuiKRQ0UDFBmjwC5YLfGtKWVNTWYK0Ve6puHK0fFI6_jJjOOdBVUG0NBz3weqIvVoh7VIaB2_CBqfROQoctoPzmWF0h5dzxvV78wvs0ZDKX70EhsL5tfWLUOQZn7ptk3m2qIQbgu2KoklCzUUKZIRAG1HhaOnbPpBYRGmc43KYzBAGD_Z0yQSyU0JVGOF9FS81tEXmittwQ',
    gpsDelta: '3.1m (Tower Triangulated)',
    hardwareClockStatus: 'Nominal',
    cvConfidence: 88.2,
    status: 'pending',
  },
];

export const ADMIN_ACTIVITY_LOGS: ActivityLogItem[] = [
  {
    id: 'log-1',
    title: 'Sec 144 Imposed: Pipalkoti Buffer',
    authInfo: 'Authorized by Col. R. Sharma • 14:22 IST',
    description: '380 SMS sirens delivered to local cell towers.',
    icon: 'emergency_share',
    iconBg: 'bg-error-container',
    iconColor: 'text-error',
  },
  {
    id: 'log-2',
    title: '4x4 Fleet Mobilized to Helang',
    authInfo: 'Dispatch Desk 2 • 13:58 IST',
    description: '6 verified volunteers assigned for fuel logistics.',
    icon: 'person_check',
    iconBg: 'bg-secondary-container',
    iconColor: 'text-primary',
  },
  {
    id: 'log-3',
    title: 'Camp Pipalkoti Capacity Cap Adjusted',
    authInfo: 'Nodal Logistics • 12:40 IST',
    description: 'Emergency threshold expanded to 1,200 cots.',
    icon: 'domain_verification',
    iconBg: 'bg-surface-container-high',
    iconColor: 'text-primary',
  },
];
