import type { HazardEntity } from './types';

export const USER_ENTITIES: Record<string, HazardEntity> = {
  joshimath: {
    id: '#UK-2024-JOS-09',
    category: 'CRITICAL • SECTION 144',
    badgeClass: 'bg-error-container text-on-error-container',
    title: 'Joshimath Ravigram Sector',
    meta: 'Geotech Sensor Array #JOS-02',
    desc: 'Severe subsurface subsidence. Inclinometer string #4 indicates active displacement of 14mm/24h. 14 residential units flagged red under Section 144.',
    telemetry: {
      fos: '0.84 Crit',
      rain: '84 mm/h',
      sat: '92% High',
      pore: '412 kPa',
      tilt: '3.8° / 24h',
    },
    directives:
      'Section 144 enforced. Civilians must immediately evacuate red-flagged structures to Gauchar Staging Hub via designated bypass.',
    img1: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=600&q=80',
    img2: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    coordinates: { lat: 30.556, lng: 79.563 },
  },
  alaknanda: {
    id: '#UK-2024-ALAK-14',
    category: 'FLASH FLOOD VECTOR',
    badgeClass: 'bg-error-container text-on-error-container',
    title: 'Alaknanda Surge: Pipalkoti Hub',
    meta: 'River Gauge Station #G-04',
    desc: 'Discharge has surged to 1,024 m³/s past safe spillway limit. High-altitude glacial lake runoffs affecting low-lying riverbanks.',
    telemetry: {
      fos: '1.02 Warn',
      rain: '112 mm/h',
      sat: '98% Sat',
      pore: '380 kPa',
      tilt: '0.9° / 24h',
    },
    directives:
      'Clear all riverbed and flood-plain settlements. Riverside pilgrimage camps barred until water recedes.',
    img1: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    img2: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=600&q=80',
    coordinates: { lat: 30.429, lng: 79.33 },
  },
  chamoli: {
    id: '#UK-2024-NH58-214',
    category: 'HIGH SLIP RISK • ROAD SEVERED',
    badgeClass: 'bg-tertiary-container text-on-tertiary-container',
    title: 'Chamoli NH-58 Blockade Slip',
    meta: 'Highway Logistics KM Post 214',
    desc: 'Talus debris slide triggered by heavy monsoonal runoff. NH-58 closed to civilian traffic. 3 PWD earth-movers actively operating on site.',
    telemetry: {
      fos: '0.78 Block',
      rain: '68 mm/h',
      sat: '88% Mod',
      pore: '340 kPa',
      tilt: '4.2° / 24h',
    },
    directives:
      'Reroute all civilian convoys through Helang bypass. Heavy commercial transport halted at Rudraprayag barrier.',
    img1: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=600&q=80',
    img2: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    coordinates: { lat: 30.512, lng: 79.521 },
  },
  shelter_gauchar: {
    id: '#SHELTER-GAUCHAR-01',
    category: 'SAFE TERMINAL • VERIFIED',
    badgeClass: 'bg-[#2e7d32]/20 text-[#1b5e20]',
    title: 'Gauchar Field Station Airstrip',
    meta: 'Designated Resettlement Hub 01',
    desc: 'Primary safe transit shelter. Capacity 200 beds (58 beds available). Equipped with medical triage, 12,000L potable water, and emergency helipad.',
    telemetry: {
      fos: '2.40 Safe',
      rain: '12 mm/h',
      sat: '22% Safe',
      pore: '40 kPa',
      tilt: '0.0° Flat',
    },
    directives:
      'Registration counters active 24/7. Immediate medical examination and dry ration kit issuance upon arrival.',
    img1: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    img2: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=600&q=80',
    coordinates: { lat: 30.291, lng: 79.155 },
  },
  sunil_ward: {
    id: '#HABITATION-SUNIL-02',
    category: 'RELOCATION • SHORT-TERM (3-12M)',
    badgeClass: 'bg-tertiary-container text-on-tertiary-container',
    title: 'Sunil Ward Upper Terrace',
    meta: 'Sector B • 630 Families',
    desc: 'Piezometer records heightened underground water pressure at 34° slope angle. Scheduled for orderly second-phase resettlement.',
    telemetry: {
      fos: '1.08 Amber',
      rain: '72 mm/h',
      sat: '78% Mod',
      pore: '280 kPa',
      tilt: '1.4° / 24h',
    },
    directives:
      'Phase 2 surveys underway. Residents requested to keep essential property records handy for SDM enumeration.',
    img1: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=600&q=80',
    img2: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    coordinates: { lat: 30.56, lng: 79.57 },
  },
  gazette: {
    id: '#UK-GOV-2024-88',
    category: 'GAZETTE NOTIFICATION',
    badgeClass: 'bg-primary-fixed text-on-primary-fixed',
    title: 'Phase 1 DBT Ex-gratia Disbursement',
    meta: 'Uttarakhand SDMA Executive Order',
    desc: '₹1.5 Lakh/family direct ex-gratia compensation released for 412 immediately displaced families of Joshimath Red Zone.',
    telemetry: {
      fos: 'N/A Gov',
      rain: 'N/A',
      sat: '412 Benef.',
      pore: '₹6.18 Cr',
      tilt: 'Oct 12 Due',
    },
    directives:
      'Ensure Aadhaar seed in bank accounts. Grievances may be filed at Chamoli SDM Camp Office or SEOC helpline 1070.',
    img1: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=600&q=80',
    img2: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    coordinates: { lat: 30.556, lng: 79.563 },
  },
};
