import type { HazardEntity } from './types';

export const USER_ENTITIES: Record<string, HazardEntity> = {
  joshimath: {
    id: '#UK-2024-JOS-09',
    category: 'CRITICAL • SECTION 144',
    badgeClass: 'bg-error-container text-on-error-container',
    title: 'Joshimath Ravigram Sector',
    meta: 'Geotech Sensor Array #JOS-02',
    desc: 'Severe subsurface subsidence. Inclinometer string #4 indicates active displacement of 14mm/24h. 14 residential units flagged red under Section 144.',
    telemetry: {
      fos: '0.84 Crit',
      rain: '84 mm/h',
      sat: '92% High',
      pore: '412 kPa',
      tilt: '3.8° / 24h',
    },
    directives:
      'Section 144 enforced. Civilians must immediately evacuate red-flagged structures to Gauchar Staging Hub via designated bypass.',
    img1: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=600&q=80',
    img2: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    coordinates: { lat: 30.556, lng: 79.563 },
  },
  alaknanda: {
    id: '#UK-2024-ALAK-14',
    category: 'FLASH FLOOD VECTOR',
    badgeClass: 'bg-error-container text-on-error-container',
    title: 'Alaknanda Surge: Pipalkoti Hub',
    meta: 'River Gauge Station #G-04',
    desc: 'Discharge has surged to 1,024 m³/s past safe spillway limit. High-altitude glacial lake runoffs affecting low-lying riverbanks.',
    telemetry: {
      fos: '1.02 Warn',
      rain: '112 mm/h',
      sat: '98% Sat',
      pore: '380 kPa',
      tilt: '0.9° / 24h',
    },
    directives:
      'Clear all riverbed and flood-plain settlements. Riverside pilgrimage camps barred until water recedes.',
    img1: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    img2: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=600&q=80',
    coordinates: { lat: 30.429, lng: 79.33 },
  },
  chamoli: {
    id: '#UK-2024-NH58-214',
    category: 'HIGH SLIP RISK • ROAD SEVERED',
    badgeClass: 'bg-tertiary-container text-on-tertiary-container',
    title: 'Chamoli NH-58 Blockade Slip',
    meta: 'Highway Logistics KM Post 214',
    desc: 'Talus debris slide triggered by heavy monsoonal runoff. NH-58 closed to civilian traffic. 3 PWD earth-movers actively operating on site.',
    telemetry: {
      fos: '0.78 Block',
      rain: '68 mm/h',
      sat: '88% Mod',
      pore: '340 kPa',
      tilt: '4.2° / 24h',
    },
    directives:
      'Reroute all civilian convoys through Helang bypass. Heavy commercial transport halted at Rudraprayag barrier.',
    img1: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=600&q=80',
    img2: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    coordinates: { lat: 30.512, lng: 79.521 },
  },
  camp_pipalkoti: {
    id: '#CAMP-SDRF-PIPAL-01',
    category: 'OPERATIONAL RELIEF CAMP • SDRF & NDRF',
    badgeClass: 'bg-emerald-700 text-white',
    title: 'SDRF & NDRF Unified Emergency Transit Camp',
    meta: 'Pipalkoti Inter-College Ground • Joint Emergency Command',
    desc: 'Frontline emergency evacuation & staging camp operated jointly by SDRF 3rd Bn, NDRF & Indian Red Cross. Provides immediate shelter pods, medical triage, hot meals, and child protection for evacuees arriving from Joshimath and Helang slips.',
    isReliefCamp: true,
    campData: {
      totalCapacity: 600,
      availableCapacity: 210,
      occupiedCapacity: 390,
      totalMedicalBeds: 40,
      availableMedicalBeds: 18,
      icuTriageBeds: 6,
      operatingAgencies: 'Uttarakhand SDRF 3rd Bn, NDRF 8th Bn & Indian Red Cross Society',
      waterReserveLiters: 16000,
      dailyWaterSupplyLiters: 5000,
      dryRationsDays: 18,
      bioToiletsCount: 24,
      powerAndComms: '15 kVA Diesel Generator + BSNL Satellite Terminal + SDRF VHF Command Link',
      ambulanceCount: 4,
      helipadDistance: '400m Drop-Zone',
      admissionProtocol: 'Immediate token registration at Gate Counter 1. Vitals screening at Red Cross medical tent. Emergency transition kits issued upon family verification.',
    },
    telemetry: {
      fos: '210/600 Free',
      rain: '18/40 Beds',
      sat: '16,000L Water',
      pore: '18d Food',
      tilt: 'SDRF Base',
    },
    directives:
      'Registration counters active 24/7. Immediate medical vitals check and family allotment token issued at Gate Counter 1. Emergency ambulance shuttle operational to Base Hospital.',
    img1: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=600&q=80',
    img2: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    coordinates: { lat: 30.432, lng: 79.334 },
  },
  camp_chamoli: {
    id: '#CAMP-DDMA-CHAMOLI-02',
    category: 'OPERATIONAL RELIEF CAMP • DDMA & NGO',
    badgeClass: 'bg-emerald-700 text-white',
    title: 'Chamoli District & NGO Humanitarian Safe Haven',
    meta: 'District Sports Complex & Grounds • DDMA & SEWA Relief',
    desc: 'Central district-level humanitarian relief camp located at the Chamoli Sports Complex. Outfitted with family cubicles, pediatric wards, psycho-social trauma counseling, 24/7 community kitchens, and Aadhaar/DBT documentation verification desks.',
    isReliefCamp: true,
    campData: {
      totalCapacity: 850,
      availableCapacity: 340,
      occupiedCapacity: 510,
      totalMedicalBeds: 60,
      availableMedicalBeds: 32,
      icuTriageBeds: 10,
      operatingAgencies: 'District Disaster Management Authority (DDMA), NDRF Logistics & SEWA International NGO',
      waterReserveLiters: 28000,
      dailyWaterSupplyLiters: 8000,
      dryRationsDays: 25,
      bioToiletsCount: 36,
      powerAndComms: '25 kW Solar Microgrid + High-Speed Emergency Wi-Fi Hub + Starlink Backup',
      ambulanceCount: 6,
      helipadDistance: 'Onsite Air Corridor',
      admissionProtocol: 'Central intake desk in main stadium pavilion. Aadhaar verification & DBT enumeration desk #4 open 08:00 - 20:00.',
    },
    telemetry: {
      fos: '340/850 Free',
      rain: '32/60 Beds',
      sat: '28,000L Water',
      pore: '25d Food',
      tilt: 'DDMA Base',
    },
    directives:
      'Central intake desk in main pavilion. Medical screening and special needs allocations at Gate 2. Hot community meal service operates continuously at Hall B.',
    img1: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    img2: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=600&q=80',
    coordinates: { lat: 30.402, lng: 79.324 },
  },
  gauchar_safe: {
    id: '#HAB-GAUCHAR-SAFE',
    category: 'GREEN ZONE • SAFE HABITATION (18.0/100)',
    badgeClass: 'bg-[#2e7d32] text-white',
    title: 'Gauchar Alluvial Tableland',
    meta: 'Broad Flat River Terrace • Resettlement Study Area',
    desc: 'Dynamic Risk Score: 18.0/100. Stable fluvial terrace over Alaknanda bedrock with FoS 10.15. Zero active slope displacement or crack propagation. Designated low-risk geographic sector for civilian resettlement evaluation.',
    riskScore: 18.0,
    zone: 'GREEN',
    riskLevel: 'LOW RISK',
    relocationPreparedness: 'Normal Monitoring',
    priorityRank: 3,
    actionProtocol:
      'Normal civic and commercial monitoring. Geotechnical surveys indicate prime bedrock stability suitable for long-term municipal planning.',
    telemetry: {
      fos: '10.15 Safe',
      rain: '0 mm/h',
      sat: '22% Safe',
      pore: '25 kPa',
      tilt: '0.0° Flat',
    },
    directives:
      'Maintain standard municipal vigilance. Continue automated inclinometer telemetry. Prime resettlement study sector.',
    img1: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    img2: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=600&q=80',
    coordinates: { lat: 30.291, lng: 79.155 },
  },
  shelter_gauchar: {
    id: '#SHELTER-GAUCHAR-01',
    category: 'SAFE TERMINAL • VERIFIED',
    badgeClass: 'bg-[#2e7d32]/20 text-[#1b5e20]',
    title: 'Gauchar Field Station Airstrip',
    meta: 'Designated Resettlement Hub 01',
    desc: 'Primary safe transit shelter. Capacity 200 beds (58 beds available). Equipped with medical triage, 12,000L potable water, and emergency helipad.',
    telemetry: {
      fos: '2.40 Safe',
      rain: '12 mm/h',
      sat: '22% Safe',
      pore: '40 kPa',
      tilt: '0.0° Flat',
    },
    directives:
      'Registration counters active 24/7. Immediate medical examination and dry ration kit issuance upon arrival.',
    img1: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    img2: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=600&q=80',
    coordinates: { lat: 30.291, lng: 79.155 },
  },
  sunil_ward: {
    id: '#HABITATION-SUNIL-02',
    category: 'RELOCATION • SHORT-TERM (3-12M)',
    badgeClass: 'bg-tertiary-container text-on-tertiary-container',
    title: 'Sunil Ward Upper Terrace',
    meta: 'Sector B • 630 Families',
    desc: 'Piezometer records heightened underground water pressure at 34° slope angle. Scheduled for orderly second-phase resettlement.',
    telemetry: {
      fos: '1.08 Amber',
      rain: '72 mm/h',
      sat: '78% Mod',
      pore: '280 kPa',
      tilt: '1.4° / 24h',
    },
    directives:
      'Phase 2 surveys underway. Residents requested to keep essential property records handy for SDM enumeration.',
    img1: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=600&q=80',
    img2: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    coordinates: { lat: 30.56, lng: 79.57 },
  },
  gazette: {
    id: '#UK-GOV-2024-88',
    category: 'GAZETTE NOTIFICATION',
    badgeClass: 'bg-primary-fixed text-on-primary-fixed',
    title: 'Phase 1 DBT Ex-gratia Disbursement',
    meta: 'Uttarakhand SDMA Executive Order',
    desc: '₹1.5 Lakh/family direct ex-gratia compensation released for 412 immediately displaced families of Joshimath Red Zone.',
    telemetry: {
      fos: 'N/A Gov',
      rain: 'N/A',
      sat: '412 Benef.',
      pore: '₹6.18 Cr',
      tilt: 'Oct 12 Due',
    },
    directives:
      'Ensure Aadhaar seed in bank accounts. Grievances may be filed at Chamoli SDM Camp Office or SEOC helpline 1070.',
    img1: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=600&q=80',
    img2: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    coordinates: { lat: 30.556, lng: 79.563 },
  },
};
